package dadkvs.server;

/* these imported classes are generated by the contract */
import dadkvs.DadkvsStep1 ;
import dadkvs.DadkvsStep1ServiceImpl ;
import io.grpc.stub.StreamObserver;

public class DadkvsStep1ServiceImpl extends Dadvs

    
    DadkvsServerState server_state;

    public DadkvsStep1ServiceImpl(DadkvsServerState state) {
	    this.server_state = state;
    }

    @Override
    public void commitorder( )
}
