package dadkvs.server;

/* these imported classes are generated by the contract */
import dadkvs.DadkvsStep1 ;
import dadkvs.DadkvsStep1ServiceGrpc;
import io.grpc.stub.StreamObserver;

public class DadkvsStep1ServiceImpl extends DadkvsStep1ServiceGrpc.DadkvsStep1ServiceImplBase {

    DadkvsServerState server_state;
    int               timestamp;
	Map<Integer, DadkvsMain.CommitRequest> request_map ;
	Map<Integer, Integer> request_order_map ;

    @Override
    public void commitorder(DadkvsStep1.commitOrderRequest request, StreamObserver<DadkvsStep1.commitOrderReply> responseObserver) {
        
    }
}

